#ifndef CONSTANTES_H_INCLUDED
#define CONSTANTES_H_INCLUDED


#define LARGEUR_FENETRE      1280
#define HAUTEUR_FENETRE      720

#define LARGEUR_CARTE        60
#define HAUTEUR_CARTE        25

#define MAX_POPULATION       25000

#define TEMPS_OEUFS          63
#define TEMPS_LARVES         81
#define TEMPS_COCONS         45
#define TEMPS_OUVRIERES      4860
#define TEMPS_REINES         16200

#define DELAY_MAJ            40
#define VITESSE_JEU          1000 // 1000 -> 1 jour = 1 seconde

enum {EST, NORD, OUEST, SUD, UNDEFINED = 0};

enum {AIR, EAU, COTON, VERRE, TUBE, BORD, ERROR = 666};

enum {OEUFS, LARVES, COCONS, TAILLE_TABLEAU_COUVAIN};

enum {OUVRIERES, TAILLE_TABLEAU_POPULATION};

enum {NBR_OEUFS, NBR_LARVES, NBR_COCONS, NBR_OUVRIERES, TAILLE_TABLEAU_NBR};

enum {EGGS, LARVAE, NYMPHS, QUEEN, WORKERS, TEMPS, JOUR, TEMPERATURE, TAILLE_TABLEAU_INFOS};

enum {PHYSIQUE, HUMIDITE, TAILLE_TABLEAU_CARTE};

enum {ZOOM1, ZOOM2, ZOOM3, NBR_ZOOM};


#endif // CONSTANTES_H_INCLUDED
